/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as LayoutLoginImport } from './routes/_layout-login'
import { Route as LayoutHomeImport } from './routes/_layout-home'
import { Route as ProjectsProjectidImport } from './routes/projects/$projectid'
import { Route as LayoutLoginSignupRouteImport } from './routes/_layout-login/signup/route'
import { Route as LayoutLoginLoginRouteImport } from './routes/_layout-login/login/route'
import { Route as LayoutHomeIndexRouteImport } from './routes/_layout-home/index/route'

// Create/Update Routes

const DashboardRoute = DashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const LayoutLoginRoute = LayoutLoginImport.update({
  id: '/_layout-login',
  getParentRoute: () => rootRoute,
} as any)

const LayoutHomeRoute = LayoutHomeImport.update({
  id: '/_layout-home',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsProjectidRoute = ProjectsProjectidImport.update({
  path: '/projects/$projectid',
  getParentRoute: () => rootRoute,
} as any)

const LayoutLoginSignupRouteRoute = LayoutLoginSignupRouteImport.update({
  path: '/signup',
  getParentRoute: () => LayoutLoginRoute,
} as any)

const LayoutLoginLoginRouteRoute = LayoutLoginLoginRouteImport.update({
  path: '/login',
  getParentRoute: () => LayoutLoginRoute,
} as any)

const LayoutHomeIndexRouteRoute = LayoutHomeIndexRouteImport.update({
  path: '/',
  getParentRoute: () => LayoutHomeRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout-home': {
      preLoaderRoute: typeof LayoutHomeImport
      parentRoute: typeof rootRoute
    }
    '/_layout-login': {
      preLoaderRoute: typeof LayoutLoginImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/_layout-home/': {
      preLoaderRoute: typeof LayoutHomeIndexRouteImport
      parentRoute: typeof LayoutHomeImport
    }
    '/_layout-login/login': {
      preLoaderRoute: typeof LayoutLoginLoginRouteImport
      parentRoute: typeof LayoutLoginImport
    }
    '/_layout-login/signup': {
      preLoaderRoute: typeof LayoutLoginSignupRouteImport
      parentRoute: typeof LayoutLoginImport
    }
    '/projects/$projectid': {
      preLoaderRoute: typeof ProjectsProjectidImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  LayoutHomeRoute.addChildren([LayoutHomeIndexRouteRoute]),
  LayoutLoginRoute.addChildren([
    LayoutLoginLoginRouteRoute,
    LayoutLoginSignupRouteRoute,
  ]),
  DashboardRoute,
  ProjectsProjectidRoute,
])

/* prettier-ignore-end */
